import type { StoreData } from "./types";

function iso(daysAgo: number, hour = 11, min = 30): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  d.setHours(hour, min, 0, 0);
  return d.toISOString();
}

export function buildSeed(): StoreData {
  return {
    users: [
      { id: "u-you", display_name: "You (Demo)", badge: 0, rank_points: 0, created_at: iso(30) },
      { id: "u-demo-giver-1", display_name: "Priya S.", badge: 4, rank_points: 12, created_at: iso(90) },
      { id: "u-demo-giver-2", display_name: "Arnab D.", badge: 2, rank_points: 5, created_at: iso(60) },
      { id: "u-demo-giver-3", display_name: "Ritu M.", badge: 1, rank_points: 2, created_at: iso(45) },
      { id: "u-steward-rashid", display_name: "Rashid (Steward)", badge: 0, rank_points: 8, created_at: iso(120) },
      { id: "u-steward-meera", display_name: "Meera K. (Steward)", badge: 0, rank_points: 6, created_at: iso(110) },
      { id: "u-steward-joy", display_name: "Joy (Steward)", badge: 0, rank_points: 4, created_at: iso(100) },
    ],
    case_pages: [
      {
        id: "c-arjun",
        alias: "Arjun",
        broad_area: "Bansdroni",
        intro_media: "c-arjun",
        intro_text:
          "Arjun is an elderly man living on a footpath near Bansdroni market. He has difficulty walking and had no family nearby. A verbal consent clip was recorded before this page opened.",
        stewards: ["u-steward-rashid", "u-steward-meera"],
        status: "active",
        consent_clip: true,
        blur_public: true,
        created_at: iso(75),
        last_update_at: iso(1),
      },
      {
        id: "c-maya",
        alias: "Maya",
        broad_area: "Garia",
        intro_media: "c-maya",
        intro_text:
          "Maya ran a small chai stall in Garia until she fell ill. She is diabetic and has no steady income. Her niece helps coordinate but cannot be present daily.",
        stewards: ["u-steward-meera", "u-steward-rashid"],
        status: "active",
        consent_clip: true,
        blur_public: false,
        created_at: iso(50),
        last_update_at: iso(12),
      },
      {
        id: "c-rahul",
        alias: "Rahul & kids",
        broad_area: "Tollygunge",
        intro_media: "c-rahul",
        intro_text:
          "Rahul's family (two kids aged 6 and 9) is temporarily staying in a rented room in Tollygunge after losing their home in a fire. Page maintained with the family's consent.",
        stewards: ["u-steward-joy"],
        status: "active",
        consent_clip: true,
        blur_public: true,
        created_at: iso(20),
        last_update_at: iso(3),
      },
    ],
    timeline: [
      // Arjun — history
      { id: "t-arj-1", case_page_id: "c-arjun", kind: "intro", text: "Page opened with recorded verbal consent. Arjun acknowledged and agreed to a blurred public profile.", author_id: "u-steward-rashid", created_at: iso(75) },
      { id: "t-arj-2", case_page_id: "c-arjun", kind: "update", text: "Winter blanket already received and is in use. Thank you to the neighbor who dropped it at the anchor point.", author_id: "u-steward-meera", created_at: iso(60) },
      { id: "t-arj-3", case_page_id: "c-arjun", kind: "fulfillment", text: "Confirmed: soap & shampoo pack handed off at Shobha Superstore.", author_id: "u-steward-rashid", need_card_id: "n-arj-hygiene-1", created_at: iso(45) },
      { id: "t-arj-4", case_page_id: "c-arjun", kind: "update", text: "Arjun had a fever last week; cost of blood work was covered by a neighbor. He is recovering.", author_id: "u-steward-rashid", created_at: iso(18) },
      // Maya — history
      { id: "t-may-1", case_page_id: "c-maya", kind: "intro", text: "Page opened. Maya agreed to share her situation. Her niece is a co-steward contact.", author_id: "u-steward-meera", created_at: iso(50) },
      { id: "t-may-2", case_page_id: "c-maya", kind: "update", text: "Maya's chai stall gear is mostly sold. She is managing day to day on help from neighbors.", author_id: "u-steward-meera", created_at: iso(30) },
      { id: "t-may-3", case_page_id: "c-maya", kind: "fulfillment", text: "Confirmed: diabetes test strips received at the local medical shop.", author_id: "u-steward-rashid", need_card_id: "n-may-med-1", created_at: iso(22) },
      // Rahul — history
      { id: "t-rah-1", case_page_id: "c-rahul", kind: "intro", text: "Family gave consent after their room fire. Kids are school-age; both parents are coordinating through steward Joy.", author_id: "u-steward-joy", created_at: iso(20) },
      { id: "t-rah-2", case_page_id: "c-rahul", kind: "update", text: "School agreed to waive this month's fees. Uniform expectations remain a gap.", author_id: "u-steward-joy", created_at: iso(10) },
      { id: "t-rah-3", case_page_id: "c-rahul", kind: "fulfillment", text: "Confirmed: two notebooks and stationery delivered.", author_id: "u-steward-joy", need_card_id: "n-rah-edu-1", created_at: iso(6) },
    ],
    anchor_points: [
      { id: "a-shobha", name: "Shobha Superstore", area: "Bansdroni", vetted_by: "u-steward-rashid", active: true },
      { id: "a-garia-mech", name: "Garia Medical Store", area: "Garia", vetted_by: "u-steward-meera", active: true },
      { id: "a-joy-teli", name: "Joy's Tea Stall", area: "Tollygunge", vetted_by: "u-steward-joy", active: true },
      { id: "a-masjid", name: "Narendrapur Community Hall", area: "Narendrapur", vetted_by: "u-steward-rashid", active: true },
    ],
    needs: [
      {
        id: "n-arj-food-1",
        media_key: "n-arj-food-1",
        ai_tags: { category: "food", item_type: "dry ration pack", urgency: "critical" },
        caption: "Arjun has no food for tonight. A week's dry ration would carry him through.",
        owner_type: "case_page",
        owner_id: "c-arjun",
        area: "Bansdroni",
        status: "open",
        quantity: "1 week's ration",
        created_at: iso(2, 9, 10),
      },
      {
        id: "n-arj-med-1",
        media_key: "n-arj-med-1",
        ai_tags: { category: "medical", item_type: "blood-pressure monitor", urgency: "high" },
        caption: "Arjun needs a blood-pressure monitor so we can check him at the page without hospital visits.",
        owner_type: "case_page",
        owner_id: "c-arjun",
        area: "Bansdroni",
        status: "open",
        quantity: "1 monitor",
        created_at: iso(4, 17, 45),
      },
      {
        id: "n-arj-hygiene-1",
        media_key: "n-arj-hygiene-1",
        ai_tags: { category: "hygiene", item_type: "soap & shampoo pack", urgency: "medium" },
        caption: "Monthly hygiene pack — soap, shampoo, towel.",
        owner_type: "case_page",
        owner_id: "c-arjun",
        area: "Bansdroni",
        status: "fulfilled",
        quantity: "1 pack",
        created_at: iso(46),
      },
      {
        id: "n-may-med-1",
        media_key: "n-may-med-1",
        ai_tags: { category: "medical", item_type: "diabetes test strips", urgency: "high" },
        caption: "Maya is out of diabetes test strips and needs a fresh month's supply.",
        owner_type: "case_page",
        owner_id: "c-maya",
        area: "Garia",
        status: "fulfilled",
        quantity: "1 month's strips",
        created_at: iso(24),
      },
      {
        id: "n-may-food-1",
        media_key: "n-may-food-1",
        ai_tags: { category: "food", item_type: "grocery bag", urgency: "high" },
        caption: "Maya's chai stall earnings stopped. A monthly grocery bag would cover basics.",
        owner_type: "case_page",
        owner_id: "c-maya",
        area: "Garia",
        status: "partially_fulfilled",
        quantity: "1 monthly bag",
        created_at: iso(8, 12, 0),
      },
      {
        id: "n-may-mobility-1",
        media_key: "n-may-mobility-1",
        ai_tags: { category: "mobility", item_type: "folding walker", urgency: "medium" },
        caption: "A folding walker would help Maya move between her room and the community kitchen.",
        owner_type: "case_page",
        owner_id: "c-maya",
        area: "Garia",
        status: "open",
        quantity: "1 walker",
        created_at: iso(15, 15, 30),
      },
      {
        id: "n-rah-clothing-1",
        media_key: "n-rah-clothing-1",
        ai_tags: { category: "clothing", item_type: "school uniform", urgency: "high" },
        caption: "Two school uniforms for the kids — sizes 6y and 9y.",
        owner_type: "case_page",
        owner_id: "c-rahul",
        area: "Tollygunge",
        status: "open",
        quantity: "2 uniforms",
        created_at: iso(1, 8, 20),
      },
      {
        id: "n-rah-edu-1",
        media_key: "n-rah-edu-1",
        ai_tags: { category: "education", item_type: "notebook bundle", urgency: "medium" },
        caption: "Notebooks and stationery for the school year.",
        owner_type: "case_page",
        owner_id: "c-rahul",
        area: "Tollygunge",
        status: "fulfilled",
        quantity: "1 bundle",
        created_at: iso(7),
      },
      {
        id: "n-rah-shelter-1",
        media_key: "n-rah-shelter-1",
        ai_tags: { category: "shelter", item_type: "warm blankets", urgency: "critical" },
        caption: "Monsoon season — the room ceiling leaks. Two waterproof sheets + warm blankets needed.",
        owner_type: "case_page",
        owner_id: "c-rahul",
        area: "Tollygunge",
        status: "open",
        quantity: "2 sheets + 2 blankets",
        created_at: iso(3),
      },
      {
        id: "n-self-elderly-cane",
        media_key: "n-self-elderly-cane",
        ai_tags: { category: "mobility", item_type: "walking stick", urgency: "medium" },
        caption: "Self-posting: our building guard, 68, needs a new walking stick after his broke.",
        owner_type: "self",
        owner_id: "u-you",
        area: "Jadavpur",
        status: "open",
        quantity: "1 stick",
        created_at: iso(5),
      },
    ],
    pledges: [
      { id: "pl-1", need_card_id: "n-arj-food-1", giver_id: "u-demo-giver-1", portion: "Full week's ration", status: "pledged", anchor_point_id: "a-shobha", created_at: iso(1, 14, 0), handed_off_at: null, confirmed_at: null },
      { id: "pl-2", need_card_id: "n-arj-food-1", giver_id: "u-demo-giver-2", portion: "Half ration", status: "cancelled", anchor_point_id: null, created_at: iso(1, 18, 0), handed_off_at: null, confirmed_at: null },
      { id: "pl-3", need_card_id: "n-arj-hygiene-1", giver_id: "u-demo-giver-2", portion: "1 pack", status: "confirmed", anchor_point_id: "a-shobha", created_at: iso(45), handed_off_at: iso(45), confirmed_at: iso(44) },
      { id: "pl-4", need_card_id: "n-may-med-1", giver_id: "u-demo-giver-1", portion: "Month's strips", status: "confirmed", anchor_point_id: "a-garia-mech", created_at: iso(24), handed_off_at: iso(23), confirmed_at: iso(22) },
      { id: "pl-5", need_card_id: "n-may-food-1", giver_id: "u-demo-giver-3", portion: "Half grocery bag", status: "handed_off", anchor_point_id: "a-garia-mech", created_at: iso(7), handed_off_at: iso(2), confirmed_at: null },
      { id: "pl-6", need_card_id: "n-rah-edu-1", giver_id: "u-demo-giver-1", portion: "Full bundle", status: "confirmed", anchor_point_id: "a-joy-teli", created_at: iso(7), handed_off_at: iso(6), confirmed_at: iso(6) },
      { id: "pl-7", need_card_id: "n-rah-shelter-1", giver_id: "u-demo-giver-3", portion: "1 blanket", status: "pledged", anchor_point_id: "a-joy-teli", created_at: iso(2, 10, 5), handed_off_at: null, confirmed_at: null },
    ],
    confirmations: [
      { id: "cn-1", pledge_id: "pl-3", need_card_id: "n-arj-hygiene-1", giver_id: "u-demo-giver-2", steward_id: "u-steward-rashid", confirmed_at: iso(44), on_chain_ref: null, mismatch_flag: false },
      { id: "cn-2", pledge_id: "pl-4", need_card_id: "n-may-med-1", giver_id: "u-demo-giver-1", steward_id: "u-steward-rashid", confirmed_at: iso(22), on_chain_ref: null, mismatch_flag: false },
      { id: "cn-3", pledge_id: "pl-6", need_card_id: "n-rah-edu-1", giver_id: "u-demo-giver-1", steward_id: "u-steward-joy", confirmed_at: iso(6), on_chain_ref: null, mismatch_flag: false },
    ],
    shares: [
      { id: "s-1", need_card_id: "n-rah-clothing-1", sharer_id: "u-demo-giver-1", at: iso(1, 9, 0) },
      { id: "s-2", need_card_id: "n-rah-clothing-1", sharer_id: "u-demo-giver-2", at: iso(1, 10, 0) },
      { id: "s-3", need_card_id: "n-rah-shelter-1", sharer_id: "u-demo-giver-1", at: iso(2, 12, 0) },
      { id: "s-4", need_card_id: "n-rah-shelter-1", sharer_id: "u-demo-giver-2", at: iso(2, 12, 30) },
      { id: "s-5", need_card_id: "n-arj-med-1", sharer_id: "u-demo-giver-3", at: iso(3, 11, 0) },
      { id: "s-6", need_card_id: "n-may-food-1", sharer_id: "u-demo-giver-1", at: iso(6, 16, 0) },
    ],
  };
}