import type { StoreData } from "./types";

function iso(daysAgo: number, hour = 11, min = 30): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  d.setHours(hour, min, 0, 0);
  return d.toISOString();
}

export function buildSeed(): StoreData {
  return {
    users: [
      { id: "u-you", display_name: "You", role: "citizen", badge: 0, honor_badge: 0, rank_points: 0, created_at: iso(30) },
      { id: "u-demo-giver-1", display_name: "Priya S.", role: "volunteer", badge: 4, honor_badge: 6, rank_points: 12, created_at: iso(90) },
      { id: "u-demo-giver-2", display_name: "Arnab D.", role: "leader", badge: 2, honor_badge: 4, rank_points: 5, created_at: iso(60) },
      { id: "u-demo-giver-3", display_name: "Ritu M.", role: "teacher", badge: 1, honor_badge: 3, rank_points: 2, created_at: iso(45) },
      { id: "u-steward-rashid", display_name: "Rashid (Steward)", role: "steward", badge: 0, honor_badge: 5, rank_points: 8, created_at: iso(120) },
      { id: "u-steward-meera", display_name: "Meera K. (NGO)", role: "ngo", badge: 0, honor_badge: 7, rank_points: 6, created_at: iso(110) },
      { id: "u-steward-joy", display_name: "Joy (Steward)", role: "steward", badge: 0, honor_badge: 3, rank_points: 4, created_at: iso(100) },
    ],
    case_pages: [
      {
        id: "c-arjun",
        alias: "Arjun",
        broad_area: "Bansdroni",
        location_label: "Near Bansdroni market, steward meets at Shobha Superstore",
        map_query: "Shobha Superstore Bansdroni Kolkata",
        intro_media: "c-arjun",
        intro_text:
          "Arjun is an elderly man living on a footpath near Bansdroni market. He has difficulty walking and had no family nearby.",
        stewards: ["u-steward-rashid", "u-steward-meera"],
        handler_type: "group",
        handler_name: "Bansdroni Helping Circle",
        status: "active",
        consent_clip: true,
        blur_public: true,
        bank_account_name: "Bansdroni Helping Circle",
        bank_name: "State Bank of India",
        bank_account_number: "XXXX-XXXX-4312",
        bank_ifsc: "SBIN0001725",
        upi_id: "bansdroni-help@upi",
        fundraiser_goal: 15000,
        government_help: "Ward office informed; no pension paperwork completed yet.",
        current_support: "Blanket and hygiene pack received; food and basic medical tracking remain open.",
        created_at: iso(75),
        last_update_at: iso(1),
      },
      {
        id: "c-maya",
        alias: "Maya",
        broad_area: "Garia",
        location_label: "Garia Medical Store handoff counter",
        map_query: "Garia Medical Store Kolkata",
        intro_media: "c-maya",
        intro_text:
          "Maya ran a small chai stall in Garia until she fell ill. She is diabetic and has no steady income. Her niece helps coordinate but cannot be present daily.",
        stewards: ["u-steward-meera", "u-steward-rashid"],
        handler_type: "ngo",
        handler_name: "Meera Community Aid",
        status: "active",
        consent_clip: true,
        blur_public: false,
        bank_account_name: "Maya Medical Support",
        bank_name: "HDFC Bank",
        bank_account_number: "XXXX-XXXX-9821",
        bank_ifsc: "HDFC0000215",
        upi_id: "maya-care@upi",
        fundraiser_goal: 22000,
        government_help: "Health card application started; medicine subsidy pending.",
        current_support: "Test strips received. Monthly grocery and mobility support remain active.",
        created_at: iso(50),
        last_update_at: iso(12),
      },
      {
        id: "c-rahul",
        alias: "Rahul & kids",
        broad_area: "Tollygunge",
        location_label: "Joy's Tea Stall, Tollygunge tram depot side",
        map_query: "Tollygunge tram depot Kolkata",
        intro_media: "c-rahul",
        intro_text:
          "Rahul's family (two kids aged 6 and 9) is temporarily staying in a rented room in Tollygunge after losing their home in a fire. Page maintained with the family's consent.",
        stewards: ["u-steward-joy"],
        handler_type: "leader",
        handler_name: "Joy local volunteer team",
        status: "active",
        consent_clip: true,
        blur_public: true,
        bank_account_name: "Rahul Family Relief",
        bank_name: "Axis Bank",
        bank_account_number: "XXXX-XXXX-7744",
        bank_ifsc: "UTIB0000312",
        upi_id: "rahul-family@upi",
        fundraiser_goal: 30000,
        government_help: "School fee waiver received for one month; fire relief not approved yet.",
        current_support: "Stationery received; uniforms, blankets and roof sheet support are still needed.",
        created_at: iso(20),
        last_update_at: iso(3),
      },
    ],
    timeline: [
      // Arjun - history
      { id: "t-arj-1", case_page_id: "c-arjun", kind: "intro", text: "Page opened with recorded verbal consent. Arjun acknowledged and agreed to a blurred public profile.", author_id: "u-steward-rashid", created_at: iso(75) },
      { id: "t-arj-2", case_page_id: "c-arjun", kind: "update", text: "Winter blanket already received and is in use. Thank you to the neighbor who dropped it at the anchor point.", author_id: "u-steward-meera", created_at: iso(60) },
      { id: "t-arj-3", case_page_id: "c-arjun", kind: "fulfillment", text: "Confirmed: soap & shampoo pack handed off at Shobha Superstore.", author_id: "u-steward-rashid", need_card_id: "n-arj-hygiene-1", created_at: iso(45) },
      { id: "t-arj-4", case_page_id: "c-arjun", kind: "update", text: "Arjun had a fever last week; cost of blood work was covered by a neighbor. He is recovering.", author_id: "u-steward-rashid", created_at: iso(18) },
      // Maya - history
      { id: "t-may-1", case_page_id: "c-maya", kind: "intro", text: "Page opened. Maya agreed to share her situation. Her niece is a co-steward contact.", author_id: "u-steward-meera", created_at: iso(50) },
      { id: "t-may-2", case_page_id: "c-maya", kind: "update", text: "Maya's chai stall gear is mostly sold. She is managing day to day on help from neighbors.", author_id: "u-steward-meera", created_at: iso(30) },
      { id: "t-may-3", case_page_id: "c-maya", kind: "fulfillment", text: "Confirmed: diabetes test strips received at the local medical shop.", author_id: "u-steward-rashid", need_card_id: "n-may-med-1", created_at: iso(22) },
      // Rahul - history
      { id: "t-rah-1", case_page_id: "c-rahul", kind: "intro", text: "Family gave consent after their room fire. Kids are school-age; both parents are coordinating through steward Joy.", author_id: "u-steward-joy", created_at: iso(20) },
      { id: "t-rah-2", case_page_id: "c-rahul", kind: "update", text: "School agreed to waive this month's fees. Uniform expectations remain a gap.", author_id: "u-steward-joy", created_at: iso(10) },
      { id: "t-rah-3", case_page_id: "c-rahul", kind: "fulfillment", text: "Confirmed: two notebooks and stationery delivered.", author_id: "u-steward-joy", need_card_id: "n-rah-edu-1", created_at: iso(6) },
    ],
    anchor_points: [
      { id: "a-shobha", name: "Shobha Superstore", area: "Bansdroni", vetted_by: "u-steward-rashid", active: true },
      { id: "a-garia-mech", name: "Garia Medical Store", area: "Garia", vetted_by: "u-steward-meera", active: true },
      { id: "a-joy-teli", name: "Joy's Tea Stall", area: "Tollygunge", vetted_by: "u-steward-joy", active: true },
      { id: "a-masjid", name: "Narendrapur Community Hall", area: "Narendrapur", vetted_by: "u-steward-rashid", active: true },
    ],
    needs: [
      {
        id: "n-arj-food-1",
        media_key: "n-arj-food-1",
        ai_tags: { category: "food", item_type: "dry ration pack", urgency: "critical" },
        caption: "Steward notice: Arjun (elderly resident near Bansdroni) has no food for tonight. A week's dry ration pack would carry him through.",
        owner_type: "case_page",
        owner_id: "c-arjun",
        area: "Bansdroni",
        status: "open",
        quantity: "1 week's ration",
        upvotes: 0,
        downvotes: 0,
        created_at: iso(2, 9, 10),
      },
      {
        id: "n-arj-med-1",
        media_key: "n-arj-med-1",
        ai_tags: { category: "medical", item_type: "blood-pressure monitor", urgency: "high" },
        caption: "Caregiver request: Arjun needs a blood-pressure monitor so our volunteer team can check his vitals locally without hospital travel.",
        owner_type: "case_page",
        owner_id: "c-arjun",
        area: "Bansdroni",
        status: "open",
        quantity: "1 monitor",
        upvotes: 0,
        downvotes: 0,
        created_at: iso(4, 17, 45),
      },
      {
        id: "n-arj-hygiene-1",
        media_key: "n-arj-hygiene-1",
        ai_tags: { category: "hygiene", item_type: "soap & shampoo pack", urgency: "medium" },
        caption: "Monthly aid request: Essential hygiene care pack (soap, antiseptic, clean towel) for Arjun.",
        owner_type: "case_page",
        owner_id: "c-arjun",
        area: "Bansdroni",
        status: "fulfilled",
        quantity: "1 pack",
        upvotes: 0,
        downvotes: 0,
        created_at: iso(46),
      },
      {
        id: "n-may-med-1",
        media_key: "n-may-med-1",
        ai_tags: { category: "medical", item_type: "diabetes test strips", urgency: "high" },
        caption: "NGO outreach for Maya: She is diabetic and out of test strips. Fresh monthly supply needed for daily sugar checks.",
        owner_type: "case_page",
        owner_id: "c-maya",
        area: "Garia",
        status: "fulfilled",
        quantity: "1 month's strips",
        upvotes: 0,
        downvotes: 0,
        created_at: iso(24),
      },
      {
        id: "n-may-food-1",
        media_key: "n-may-food-1",
        ai_tags: { category: "food", item_type: "grocery bag", urgency: "high" },
        caption: "Volunteer notice: Maya's small chai stall closed due to illness. A monthly grocery pack covers her basic nutrition.",
        owner_type: "case_page",
        owner_id: "c-maya",
        area: "Garia",
        status: "partially_fulfilled",
        quantity: "1 monthly bag",
        upvotes: 0,
        downvotes: 0,
        created_at: iso(8, 12, 0),
      },
      {
        id: "n-may-mobility-1",
        media_key: "n-may-mobility-1",
        ai_tags: { category: "mobility", item_type: "folding walker", urgency: "medium" },
        caption: "Steward request: A lightweight folding walker to help Maya move safely between her room and clinic checkups.",
        owner_type: "case_page",
        owner_id: "c-maya",
        area: "Garia",
        status: "open",
        quantity: "1 walker",
        upvotes: 0,
        downvotes: 0,
        created_at: iso(15, 15, 30),
      },
      {
        id: "n-rah-clothing-1",
        media_key: "n-rah-clothing-1",
        ai_tags: { category: "clothing", item_type: "school uniform", urgency: "high" },
        caption: "Disaster relief: Two school uniforms (sizes 6y & 9y) needed for Rahul's two young children after recent fire damage.",
        owner_type: "case_page",
        owner_id: "c-rahul",
        area: "Tollygunge",
        status: "open",
        quantity: "2 uniforms",
        upvotes: 0,
        downvotes: 0,
        created_at: iso(1, 8, 20),
      },
      {
        id: "n-rah-edu-1",
        media_key: "n-rah-edu-1",
        ai_tags: { category: "education", item_type: "notebook bundle", urgency: "medium" },
        caption: "Education aid: Notebooks, pencils, and school stationery pack for Rahul's children to continue studies.",
        owner_type: "case_page",
        owner_id: "c-rahul",
        area: "Tollygunge",
        status: "fulfilled",
        quantity: "1 bundle",
        upvotes: 0,
        downvotes: 0,
        created_at: iso(7),
      },
      {
        id: "n-rah-shelter-1",
        media_key: "n-rah-shelter-1",
        ai_tags: { category: "shelter", item_type: "warm blankets", urgency: "critical" },
        caption: "Emergency weather relief: Two waterproof tarpaulin sheets and warm blankets needed for fire-displaced family.",
        owner_type: "case_page",
        owner_id: "c-rahul",
        area: "Tollygunge",
        status: "open",
        quantity: "2 sheets + 2 blankets",
        upvotes: 0,
        downvotes: 0,
        created_at: iso(3),
      },
      {
        id: "n-self-elderly-cane",
        media_key: "n-self-elderly-cane",
        ai_tags: { category: "mobility", item_type: "walking stick", urgency: "medium" },
        caption: "Community advocate request: Need a sturdy walking cane for Uncle Ramu (local night guard, 68) after a knee injury on duty.",
        owner_type: "self",
        owner_id: "u-demo-giver-1",
        area: "Jadavpur",
        status: "open",
        quantity: "1 stick",
        upvotes: 0,
        downvotes: 0,
        created_at: iso(5),
      },
      {
        id: "n-behala-infant-1",
        media_key: "n-behala-infant-1",
        ai_tags: { category: "hygiene", item_type: "newborn care kit", urgency: "high" },
        caption: "Urgent infant aid: Newborn hygiene care kit with gentle baby soap, moisturizing lotion, organic cotton towels and diapers for baby girl in Behala.",
        owner_type: "self",
        owner_id: "u-demo-giver-1",
        area: "Behala",
        status: "open",
        quantity: "1 newborn kit",
        upvotes: 0,
        downvotes: 0,
        created_at: iso(1, 4, 15),
      },
      {
        id: "n-naren-water-1",
        media_key: "n-naren-water-1",
        ai_tags: { category: "food", item_type: "water filter dispenser", urgency: "critical" },
        caption: "Clean drinking water access: Stainless steel gravity water filter container dispenser needed for community daycare center in Narendrapur.",
        owner_type: "case_page",
        owner_id: "c-arjun",
        area: "Narendrapur",
        status: "open",
        quantity: "1 filtration unit",
        upvotes: 0,
        downvotes: 0,
        created_at: iso(1, 11, 30),
      },
      {
        id: "n-jad-textbooks-1",
        media_key: "n-jad-textbooks-1",
        ai_tags: { category: "education", item_type: "science & math textbooks", urgency: "medium" },
        caption: "Secondary education aid: Higher mathematics and science textbook bundle with study notebooks for 10th-grade student Amit.",
        owner_type: "self",
        owner_id: "u-demo-giver-3",
        area: "Jadavpur",
        status: "open",
        quantity: "1 textbook set",
        upvotes: 0,
        downvotes: 0,
        created_at: iso(2, 6, 0),
      },
      {
        id: "n-gar-sweaters-1",
        media_key: "n-gar-sweaters-1",
        ai_tags: { category: "clothing", item_type: "wool sweaters & jackets", urgency: "high" },
        caption: "Seasonal warmth initiative: Warm knitted wool sweaters and thermal jackets for elderly night workers in Garia.",
        owner_type: "case_page",
        owner_id: "c-maya",
        area: "Garia",
        status: "open",
        quantity: "3 sweaters (M & L)",
        upvotes: 0,
        downvotes: 0,
        created_at: iso(2, 16, 45),
      },
      {
        id: "n-tolly-cushion-1",
        media_key: "n-tolly-cushion-1",
        ai_tags: { category: "mobility", item_type: "orthopedic wheelchair cushion", urgency: "high" },
        caption: "Mobility support: Orthopedic memory-foam pressure relief wheelchair seat cushion for Uncle Dipak in Tollygunge.",
        owner_type: "case_page",
        owner_id: "c-rahul",
        area: "Tollygunge",
        status: "open",
        quantity: "1 cushion",
        upvotes: 0,
        downvotes: 0,
        created_at: iso(3, 14, 20),
      },
    ],
    pledges: [
      { id: "pl-1", need_card_id: "n-arj-food-1", giver_id: "u-demo-giver-1", portion: "Full week's ration", status: "pledged", anchor_point_id: "a-shobha", created_at: iso(1, 14, 0), handed_off_at: null, confirmed_at: null },
      { id: "pl-2", need_card_id: "n-arj-food-1", giver_id: "u-demo-giver-2", portion: "Half ration", status: "cancelled", anchor_point_id: null, created_at: iso(1, 18, 0), handed_off_at: null, confirmed_at: null },
      { id: "pl-3", need_card_id: "n-arj-hygiene-1", giver_id: "u-demo-giver-2", portion: "1 pack", status: "confirmed", anchor_point_id: "a-shobha", created_at: iso(45), handed_off_at: iso(45), confirmed_at: iso(44) },
      { id: "pl-4", need_card_id: "n-may-med-1", giver_id: "u-demo-giver-1", portion: "Month's strips", status: "confirmed", anchor_point_id: "a-garia-mech", created_at: iso(24), handed_off_at: iso(23), confirmed_at: iso(22) },
      { id: "pl-5", need_card_id: "n-may-food-1", giver_id: "u-demo-giver-3", portion: "Half grocery bag", status: "handed_off", anchor_point_id: "a-garia-mech", created_at: iso(7), handed_off_at: iso(2), confirmed_at: null },
      { id: "pl-6", need_card_id: "n-rah-edu-1", giver_id: "u-demo-giver-1", portion: "Full bundle", status: "confirmed", anchor_point_id: "a-joy-teli", created_at: iso(7), handed_off_at: iso(6), confirmed_at: iso(6) },
      { id: "pl-7", need_card_id: "n-rah-shelter-1", giver_id: "u-demo-giver-3", portion: "1 blanket", status: "pledged", anchor_point_id: "a-joy-teli", created_at: iso(2, 10, 5), handed_off_at: null, confirmed_at: null },
    ],
    confirmations: [
      { id: "cn-1", pledge_id: "pl-3", need_card_id: "n-arj-hygiene-1", giver_id: "u-demo-giver-2", steward_id: "u-steward-rashid", confirmed_at: iso(44), on_chain_ref: null, mismatch_flag: false },
      { id: "cn-2", pledge_id: "pl-4", need_card_id: "n-may-med-1", giver_id: "u-demo-giver-1", steward_id: "u-steward-rashid", confirmed_at: iso(22), on_chain_ref: null, mismatch_flag: false },
      { id: "cn-3", pledge_id: "pl-6", need_card_id: "n-rah-edu-1", giver_id: "u-demo-giver-1", steward_id: "u-steward-joy", confirmed_at: iso(6), on_chain_ref: null, mismatch_flag: false },
    ],
    shares: [
      { id: "s-1", need_card_id: "n-rah-clothing-1", sharer_id: "u-demo-giver-1", at: iso(1, 9, 0) },
      { id: "s-2", need_card_id: "n-rah-clothing-1", sharer_id: "u-demo-giver-2", at: iso(1, 10, 0) },
      { id: "s-3", need_card_id: "n-rah-shelter-1", sharer_id: "u-demo-giver-1", at: iso(2, 12, 0) },
      { id: "s-4", need_card_id: "n-rah-shelter-1", sharer_id: "u-demo-giver-2", at: iso(2, 12, 30) },
      { id: "s-5", need_card_id: "n-arj-med-1", sharer_id: "u-demo-giver-3", at: iso(3, 11, 0) },
      { id: "s-6", need_card_id: "n-may-food-1", sharer_id: "u-demo-giver-1", at: iso(6, 16, 0) },
    ],
    reactions: [
      { id: "r-1", need_card_id: "n-arj-food-1", user_id: "u-demo-giver-1", kind: "urgent", at: iso(1, 9, 15) },
      { id: "r-2", need_card_id: "n-rah-clothing-1", user_id: "u-demo-giver-3", kind: "support", at: iso(1, 10, 20) },
      { id: "r-3", need_card_id: "n-may-food-1", user_id: "u-steward-rashid", kind: "pray", at: iso(4, 13, 10) },
    ],
    donations: [
      { id: "d-1", case_page_id: "c-arjun", donor_id: "u-demo-giver-1", donor_name: "Priya S.", amount: 1500, method: "upi", note: "Food fund for one week", at: iso(2, 15, 0) },
      { id: "d-1b", case_page_id: "c-arjun", donor_id: "u-demo-giver-2", donor_name: "Debashis K.", amount: 2500, method: "bank", note: "Medicines and knee brace support", at: iso(3, 11, 20) },
      { id: "d-1c", case_page_id: "c-arjun", donor_id: "u-steward-meera", donor_name: "Bansdroni Welfare", amount: 2000, method: "upi", note: "Dry ration bundle aid", at: iso(5, 14, 10) },
      { id: "d-1d", case_page_id: "c-arjun", donor_id: "u-demo-giver-3", donor_name: "Souvik M.", amount: 800, method: "upi", note: "Walking cane and socks contribution", at: iso(6, 18, 40) },
      { id: "d-2", case_page_id: "c-maya", donor_id: "u-demo-giver-2", donor_name: "Arnab D.", amount: 2500, method: "bank", note: "Diabetes medicine support", at: iso(6, 11, 30) },
      { id: "d-2b", case_page_id: "c-maya", donor_id: "u-demo-giver-1", donor_name: "Sneha R.", amount: 1800, method: "upi", note: "Insulin & blood glucose strips", at: iso(8, 10, 15) },
      { id: "d-2c", case_page_id: "c-maya", donor_id: "u-steward-rashid", donor_name: "Dr. B. Sen", amount: 3000, method: "bank", note: "Specialist health checkup fund", at: iso(10, 16, 0) },
      { id: "d-3", case_page_id: "c-rahul", donor_id: "u-demo-giver-3", donor_name: "Ritu M.", amount: 1000, method: "cash", note: "School copies and pencils", at: iso(7, 16, 45) },
      { id: "d-3b", case_page_id: "c-rahul", donor_id: "u-demo-giver-1", donor_name: "Subhasis B.", amount: 2000, method: "upi", note: "Textbooks and geometry sets", at: iso(9, 13, 30) },
      { id: "d-3c", case_page_id: "c-rahul", donor_id: "u-demo-giver-2", donor_name: "Tollygunge Youth", amount: 1500, method: "upi", note: "Uniform sets and footwear", at: iso(12, 17, 20) },
    ],
    offers: [
      { id: "o-1", user_id: "u-demo-giver-3", title: "Roadside evening lessons for children", category: "time", area: "Tollygunge", quantity: "3 evenings per week", contact: "Ritu through steward Joy", status: "available", created_at: iso(3) },
      { id: "o-2", user_id: "u-demo-giver-1", title: "Used school books, class 1 to 4", category: "education", area: "Garia", quantity: "2 bundles", contact: "Priya via anchor point", status: "available", created_at: iso(5) },
      { id: "o-3", user_id: "u-demo-giver-2", title: "Dry ration packets", category: "food", area: "Bansdroni", quantity: "5 packets", contact: "Arnab community desk", status: "available", created_at: iso(1) },
    ],
    case_messages: [
      { id: "m-1", case_page_id: "c-rahul", author_id: "u-demo-giver-3", text: "I can teach both children basic English and maths twice this week.", created_at: iso(2, 18, 10) },
      { id: "m-2", case_page_id: "c-arjun", author_id: "u-steward-meera", text: "Please route all food drops through Shobha Superstore after 6 PM.", created_at: iso(1, 12, 30) },
      { id: "m-3", case_page_id: "c-maya", author_id: "u-demo-giver-2", text: "Can someone confirm if the health-card form still needs photos?", created_at: iso(3, 9, 20) },
    ],
    comments: [],
    votes: [],
    volunteers: [],
    follows: [
      { id: "f-1", user_id: "u-you", followee_type: "case", followee_id: "c-arjun", want_updates: true, created_at: iso(4) },
      { id: "f-2", user_id: "u-demo-giver-1", followee_type: "user", followee_id: "u-steward-meera", want_updates: true, created_at: iso(5) },
    ],
    notifications: [
      { id: "nt-1", user_id: "u-you", kind: "good_news", target_id: "c-arjun", case_page_id: "c-arjun", text: "Arjun's blood-pressure monitor request was fulfilled and the monitor is in use.", read: false, created_at: iso(1, 12, 5) },
      { id: "nt-2", user_id: "u-you", kind: "case_update", target_id: "c-arjun", case_page_id: "c-arjun", text: "New update on Arjun's case: medicine and blood work costs were covered by a neighbor.", read: false, created_at: iso(0, 9, 40) },
    ],
    achievements: [
      {
        id: "a-1",
        case_page_id: "c-arjun",
        title: "A warm winter for Arjun",
        text: "After neighbors delivered a winter blanket and a hygiene pack, Arjun's health stabilized. A follow-up found him sleeping safer and checking his vitals regularly now that a blood-pressure monitor is in use.",
        by_name: "Bansdroni Helping Circle",
        highlight: "Arjun",
        created_at: iso(30),
      },
      {
        id: "a-2",
        case_page_id: "c-maya",
        title: "Maya's chai stall plans are back",
        text: "Monthly grocery packs and diabetes test strips kept Maya nourished while she recovered. Her niece reports Maya is now planning to restart a small tea stall with community support.",
        by_name: "Meera Community Aid",
        highlight: "Maya",
        created_at: iso(15),
      },
      {
        id: "a-3",
        case_page_id: "c-rahul",
        title: "Back to school for Rahul's kids",
        text: "Stationery, uniforms and a school fee waiver meant both children returned to class two weeks after the fire. The school confirmed they are attending regularly.",
        by_name: "Joy local volunteer team",
        highlight: "Rahul & kids",
        created_at: iso(6),
      },
    ],
  };
}
